### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `typos --hidden --format brief`

### CODE REVIEW

**Comment by WGUNDERWOOD** [comment]
Thanks for this! A couple of comments:
- "Fulfilment" is standard spelling in British English.
- "Reuse" is commonplace so I think we should leave this as is.
- "Intensional" is correct in the contex of type theory.

Could you revert these back and make a new commit?

**Comment by WGUNDERWOOD** [comment]
Fixes look good, could you remove the `_typos.toml` file?

**Comment by WGUNDERWOOD** [comment]
Thanks for this!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
