### PR TITLE
Split sectioning commands onto new lines

### PR DESCRIPTION
**Pull request by cdesaintguilhem**
These changes introduce a couple of new regexes to match sectioning commands and capture them in order to split them onto new lines. This PR replaces #36 by introducing the test files together with the code to handle them and addresses [this comment](https://github.com/WGUNDERWOOD/tex-fmt/issues/13#issuecomment-2397109673) from #13.

One change from the test files in #36 is that text that follows a sectioning command is not expected to also be split onto a new line. I realised that this might be tricky to catch with regex if there are more groups of opening and closing brackets within the sectioning command. (Imagine something like `\section{The \emph{best} section}`.

I will first mark this PR as draft so that we can discuss whether capturing trailing text should also be included in this PR or in a later one.

### CODE REVIEW

**Comment by WGUNDERWOOD** [comment]
Thanks for this. Do you cover non-numbered cases such as `\section*{}`?

**Comment by cdesaintguilhem** [comment]
Ah, good catch on non-numbered cases! I've now updated the regexes and expanded the test file to cover these too.

**Comment by WGUNDERWOOD** [comment]
Perhaps we can try to formulate this in a way that does not duplicate all the `\section`, `\part`... commands? It will otherwise be difficult to maintain. For example, compare with the current implementation of `LISTS` and `LISTS_BEGIN` in `regexes.rs`: each environment is defined once in a const array, then iterated over to construct the objects for matching.

**Comment by cdesaintguilhem** [comment]
Yes that's a good point. I'll look into it this week hopefully.

**Comment by WGUNDERWOOD** [comment]
Thanks for your help here, I'm going to merge this now so we have the functionality. However I would like to simplify the implementation a little. Could you help me understand whether it will be possible to merge all the logic and regexes for sectioning and environments? It seems to me that they are treated the same.

**Comment by cdesaintguilhem** [comment]
Regarding the implementation: I will open an issue to keep track of this.

Regarding the performance: I measure ~56ms on my machine both before and after the merge, but I'll double-check this.

**Comment by WGUNDERWOOD** [comment]
I have added few extra commits since the merge -- see 8236d5a465dbcace69f2079b4876987cd5ada2f1. Performance is now closer to how it was on my machine, mainly by making `Pattern::new()` more efficient. I've also merged the implementations of sectioning and environments logic.

**Comment by cdesaintguilhem** [comment]
Thanks for pointing those out! Indeed I now measure 49ms on my machine, much closer to what it was before.

And after taking a quick look at the merge of the implementations, that's pretty much what I had in mind, so I don't think opening the issue is necessary for the moment.

**Pull request merged**
